stateDiagram-v2
    direction LR

    Build: Build Interaction
    Request: Set Expected Request
    Response: Set Expected Response
    Register: Register Interaction
    Mock: Start Mock Server
    Send: Send Request
    Verify: Verify Interactions
    Assert: Assert Verification
    Write: Write Pact File

    [*] --> Build
    state Build {
        direction LR

        [*] --> Request
        [*] --> Response
        Request --> [*]
        Response --> [*]
    }
    Build --> Register
    Register --> Mock
    Mock --> Send
    Send --> Verify
    Verify --> Assert
    Assert --> Write
    Write --> [*]
