sequenceDiagram
    participant Pact Broker
    participant Verifier
    participant Server
    Verifier->>Pact Broker: Get Pacts
    activate Verifier
    activate Server
    Pact Broker-->>Verifier: Pacts
    rect rgb(0, 150, 0)
    loop Every pacts
        rect rgb(200, 100, 255)
        loop Every interactions in pact
                Verifier->>Server: Setup provider state
                Verifier->>Server: Send request
                Server-->>Verifier: Response
                Verifier-->>Verifier: Collect Matches & Mismatches
                Verifier->>Server: Teardown provider state
        end
        end
    end
    end
    Verifier->>Pact Broker: Publish Verification Results
    deactivate Server
    deactivate Verifier
