@startuml

[Consumer] as consumer
[Provider] as provider
node "Pact Broker" as broker {
  database DB
}
consumer -right--> broker: define and publish contracts
broker -right--> provider: pull contracts and verify
@enduml
